### ISSUE TITLE
Integrar controles con predicciones

### ISSUE THREAD

**Issue by LorenRd** [LorenRd/mario-tfjs#13]

**Comment by amgdev9** [comment]
Tocar solamente el archivo /util/input.js, la predicción se saca de Redux: store.getState().DataReducer.prediction tiene el string con la clase predecida.

Se toma una predicción por frame, para prevenir errores, a lo mejor hace falta coger de cada 5 predicciones la que más haya salido.

Puede ser interesante añadir un gesto para estar quieto.
